apiVersion: v1
kind: Pod
metadata:
  name: nginx-tol-aff
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.type
            operator: In
            values:
            - b
  tolerations:
  - key: "node.type"
    operator: "Equal"
    value: "b"
    effect: "NoSchedule"